name: App Build & Deploy

on:
  push:
    branches: [main]
    paths:
    - 'helm/**'
    - 'main.py'
    - 'risk_engine/**'
    - 'ml_inference/**'
    - 'alerting/**'
    - 'Dockerfile'
  pull_request:
   branches: [main]
   paths:
    - 'helm/**'
    - 'main.py'
    - 'risk_engine/**'
    - 'ml_inference/**'
    - 'alerting/**'

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: 026703081738.dkr.ecr.eu-north-1.amazonaws.com
jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install ruff pytest

      - name: Lint
        run: ruff check main.py risk_engine/ ml_inference/ alerting/

      - name: Helm Lint
        run: |
          helm lint helm/rtrp-app
       

  build-and-push:
    name: Build & Push Images
    needs: lint-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
     matrix:
      include:
      - service: trade-api
        dockerfile: Dockerfile
        context: .
      - service: risk-engine
        dockerfile: risk_engine/Dockerfile
        context: risk_engine
      - service: ml-inference
        dockerfile: ml_inference/Dockerfile
        context: ml_inference
      - service: alerting
        dockerfile: alerting/Dockerfile
        context: alerting
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build and Push
        run: |
         IMAGE=${{ env.ECR_REGISTRY }}/rtrp-${{ matrix.service }}:${{ github.sha }}
         docker build -t $IMAGE -f ${{ matrix.dockerfile }} ${{ matrix.context }}
         docker push $IMAGE

  deploy:
    name: Update Helm Values
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update image tag in values.yaml
        run: |
          sed -i "s|tag:.*|tag: \"${{ github.sha }}\"|" helm/rtrp-app/values.yaml

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/rtrp-app/values.yaml
          git commit -m "chore: update image tag to ${{ github.sha }} [skip ci]"
          git push